### ISSUE TITLE
vagrant up stuck in the middle and never compete

### ISSUE THREAD

**Issue by cocacolabe** [udacity/OAuth2.0#8]
Hi there,

I'm on Lesson 12 "Creating Google sign in class" -Step 0 Get initial app running

After download the Oauth folder I run vagrant up

However, it stuck in the middle and never finished.

I'll post the code here, it's very long...

Please help me fix this issue, thanks!

[20:54:01] (master) oauth
// :heart: vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-16.04-i386'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-16.04-i386' is up to date...
==> default: Setting the name of the VM: oauth_default_1497660865206_32316
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
default: Adapter 1: nat
==> default: Forwarding ports...
default: 5000 (guest) => 5000 (host) (adapter 1)
default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
default: SSH address: 127.0.0.1:2222
default: SSH username: vagrant
default: SSH auth method: private key
default: 
default: Vagrant insecure key detected. Vagrant will automatically replace
default: this with a newly generated keypair for better security.
default: 
default: Inserting generated public key within guest...
default: Removing insecure key from the guest if it's present...
default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
default: /vagrant => /Users/tingsmac/Downloads/FSND-Virtual-Machine/vagrant/oauth
==> default: Running provisioner: shell...
default: Running: /var/folders/48/yzxpkqqx5gsb4sj5qx1b6brc0000gn/T/vagrant-shell20170616-4545-1x423ug.sh
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../bash_4.3-14ubuntu1.2_i386.deb ...
==> default: Unpacking bash (4.3-14ubuntu1.2) over (4.3-14ubuntu1.1) ...
==> default: Processing triggers for install-info (6.1.0.dfsg.1-5) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Setting up bash (4.3-14ubuntu1.2) ...
==> default: update-alternatives: 
==> default: using /usr/share/man/man7/bash-builtins.7.gz to provide /usr/share/man/man7/builtins.7.gz (builtins.7.gz) in auto mode
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../login_1%3a4.2-3.1ubuntu5.3_i386.deb ...
==> default: Unpacking login (1:4.2-3.1ubuntu5.3) over (1:4.2-3.1ubuntu5) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Setting up login (1:4.2-3.1ubuntu5.3) ...
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../systemd-sysv_229-4ubuntu17_i386.deb ...
==> default: Unpacking systemd-sysv (229-4ubuntu17) over (229-4ubuntu16) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Setting up systemd-sysv (229-4ubuntu17) ...
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../libpam-systemd_229-4ubuntu17_i386.deb ...
==> default: Unpacking libpam-systemd:i386 (229-4ubuntu17) over (229-4ubuntu16) ...
==> default: Preparing to unpack .../libsystemd0_229-4ubuntu17_i386.deb ...
==> default: Unpacking libsystemd0:i386 (229-4ubuntu17) over (229-4ubuntu16) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: Setting up libsystemd0:i386 (229-4ubuntu17) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../systemd_229-4ubuntu17_i386.deb ...
==> default: Unpacking systemd (229-4ubuntu17) over (229-4ubuntu16) ...
==> default: Processing triggers for dbus (1.10.6-1ubuntu3.3) ...
==> default: Processing triggers for ureadahead (0.100.0-19) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Setting up systemd (229-4ubuntu17) ...
==> default: addgroup: 
==> default: The group systemd-journal' already exists as a system group. Exiting.
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../udev_229-4ubuntu17_i386.deb ...
==> default: Unpacking udev (229-4ubuntu17) over (229-4ubuntu16) ...
==> default: Preparing to unpack .../libudev1_229-4ubuntu17_i386.deb ...
==> default: Unpacking libudev1:i386 (229-4ubuntu17) over (229-4ubuntu16) ...
==> default: Processing triggers for systemd (229-4ubuntu17) ...
==> default: Processing triggers for ureadahead (0.100.0-19) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: Setting up libudev1:i386 (229-4ubuntu17) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../grub-pc_2.02~beta2-36ubuntu3.11_i386.deb ...
==> default: Unpacking grub-pc (2.02~beta2-36ubuntu3.11) over (2.02~beta2-36ubuntu3.9) ...
==> default: Preparing to unpack .../grub-pc-bin_2.02~beta2-36ubuntu3.11_i386.deb ...
==> default: Unpacking grub-pc-bin (2.02~beta2-36ubuntu3.11) over (2.02~beta2-36ubuntu3.9) ...
==> default: Preparing to unpack .../grub2-common_2.02~beta2-36ubuntu3.11_i386.deb ...
==> default: Unpacking grub2-common (2.02~beta2-36ubuntu3.11) over (2.02~beta2-36ubuntu3.9) ...
==> default: Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-2ubuntu4.1_i386.deb ...
==> default: Unpacking zlib1g-dev:i386 (1:1.2.8.dfsg-2ubuntu4.1) over (1:1.2.8.dfsg-2ubuntu4) ...
==> default: Preparing to unpack .../zlib1g_1%3a1.2.8.dfsg-2ubuntu4.1_i386.deb ...
==> default: Unpacking zlib1g:i386 (1:1.2.8.dfsg-2ubuntu4.1) over (1:1.2.8.dfsg-2ubuntu4) ...
==> default: Processing triggers for install-info (6.1.0.dfsg.1-5) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: Setting up zlib1g:i386 (1:1.2.8.dfsg-2ubuntu4.1) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../libfreetype6_2.6.1-0.1ubuntu2.3_i386.deb ...
==> default: Unpacking libfreetype6:i386 (2.6.1-0.1ubuntu2.3) over (2.6.1-0.1ubuntu2.2) ...
==> default: Preparing to unpack .../grub-common_2.02~beta2-36ubuntu3.11_i386.deb ...
==> default: Unpacking grub-common (2.02~beta2-36ubuntu3.11) over (2.02~beta2-36ubuntu3.9) ...
==> default: Preparing to unpack .../openssh-sftp-server_1%3a7.2p2-4ubuntu2.2_i386.deb ...
==> default: Unpacking openssh-sftp-server (1:7.2p2-4ubuntu2.2) over (1:7.2p2-4ubuntu2.1) ...
==> default: Preparing to unpack .../libssl-dev_1.0.2g-1ubuntu4.8_i386.deb ...
==> default: Unpacking libssl-dev:i386 (1.0.2g-1ubuntu4.8) over (1.0.2g-1ubuntu4.6) ...
==> default: Preparing to unpack .../libssl1.0.0_1.0.2g-1ubuntu4.8_i386.deb ...
==> default: Unpacking libssl1.0.0:i386 (1.0.2g-1ubuntu4.8) over (1.0.2g-1ubuntu4.6) ...
==> default: Preparing to unpack .../openssh-server_1%3a7.2p2-4ubuntu2.2_i386.deb ...
==> default: Unpacking openssh-server (1:7.2p2-4ubuntu2.2) over (1:7.2p2-4ubuntu2.1) ...
==> default: Preparing to unpack .../passwd_1%3a4.2-3.1ubuntu5.3_i386.deb ...
==> default: Unpacking passwd (1:4.2-3.1ubuntu5.3) over (1:4.2-3.1ubuntu5) ...
==> default: Processing triggers for libc-bin (2.23-0ubuntu7) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Processing triggers for systemd (229-4ubuntu17) ...
==> default: Processing triggers for ureadahead (0.100.0-19) ...
==> default: Processing triggers for ufw (0.35-0ubuntu2) ...
==> default: Setting up passwd (1:4.2-3.1ubuntu5.3) ...
==> default: (Reading database ... 
==> default: (Reading database ... 5%
==> default: (Reading database ... 10%
==> default: (Reading database ... 15%
==> default: (Reading database ... 20%
==> default: (Reading database ... 25%
==> default: (Reading database ... 30%
==> default: (Reading database ... 35%
==> default: (Reading database ... 40%
==> default: (Reading database ... 45%
==> default: (Reading database ... 50%
==> default: (Reading database ... 55%
==> default: (Reading database ... 60%
==> default: (Reading database ... 65%
==> default: (Reading database ... 70%
==> default: (Reading database ... 75%
==> default: (Reading database ... 80%
==> default: (Reading database ... 85%
==> default: (Reading database ... 90%
==> default: (Reading database ... 95%
==> default: (Reading database ... 100%
==> default: (Reading database ... 
==> default: 37928 files and directories currently installed.)
==> default: Preparing to unpack .../openssh-client_1%3a7.2p2-4ubuntu2.2_i386.deb ...
==> default: Unpacking openssh-client (1:7.2p2-4ubuntu2.2) over (1:7.2p2-4ubuntu2.1) ...
==> default: Preparing to unpack .../ubuntu-core-launcher_2.25_i386.deb ...
==> default: Unpacking ubuntu-core-launcher (2.25) over (2.24.1) ...
==> default: Preparing to unpack .../archives/snapd_2.25_i386.deb ...
==> default: Warning: Stopping snapd.service, but it can still be activated by:
==> default: snapd.socket
==> default: Unpacking snapd (2.25) over (2.24.1) ...
==> default: Preparing to unpack .../iproute2_4.3.0-1ubuntu3.16.04.1_i386.deb ...
==> default: Unpacking iproute2 (4.3.0-1ubuntu3.16.04.1) over (4.3.0-1ubuntu3) ...
==> default: Preparing to unpack .../isc-dhcp-client_4.3.3-5ubuntu12.7_i386.deb ...
==> default: Unpacking isc-dhcp-client (4.3.3-5ubuntu12.7) over (4.3.3-5ubuntu12.6) ...
==> default: Preparing to unpack .../isc-dhcp-common_4.3.3-5ubuntu12.7_i386.deb ...
==> default: Unpacking isc-dhcp-common (4.3.3-5ubuntu12.7) over (4.3.3-5ubuntu12.6) ...
==> default: Preparing to unpack .../libtasn1-6_4.7-3ubuntu0.16.04.2_i386.deb ...
==> default: Unpacking libtasn1-6:i386 (4.7-3ubuntu0.16.04.2) over (4.7-3ubuntu0.16.04.1) ...
==> default: Preparing to unpack .../libgnutls-openssl27_3.4.10-4ubuntu1.3_i386.deb ...
==> default: Unpacking libgnutls-openssl27:i386 (3.4.10-4ubuntu1.3) over (3.4.10-4ubuntu1.2) ...
==> default: Preparing to unpack .../libgnutls30_3.4.10-4ubuntu1.3_i386.deb ...
==> default: Unpacking libgnutls30:i386 (3.4.10-4ubuntu1.3) over (3.4.10-4ubuntu1.2) ...
==> default: Preparing to unpack .../logrotate_3.8.7-2ubuntu2.16.04.1_i386.deb ...
==> default: Unpacking logrotate (3.8.7-2ubuntu2.16.04.1) over (3.8.7-2ubuntu2) ...
==> default: Preparing to unpack .../sudo_1.8.16-0ubuntu1.4_i386.deb ...
==> default: Unpacking sudo (1.8.16-0ubuntu1.4) over (1.8.16-0ubuntu1.3) ...
==> default: Preparing to unpack .../libicu55_55.1-7ubuntu0.2_i386.deb ...
==> default: Unpacking libicu55:i386 (55.1-7ubuntu0.2) over (55.1-7ubuntu0.1) ...
==> default: Preparing to unpack .../libldap-2.4-2_2.4.42+dfsg-2ubuntu3.2_i386.deb ...
==> default: Unpacking libldap-2.4-2:i386 (2.4.42+dfsg-2ubuntu3.2) over (2.4.42+dfsg-2ubuntu3.1) ...
==> default: Preparing to unpack .../librtmp1_2.4+20151223.gitfa8646d-1ubuntu0.1_i386.deb ...
==> default: Unpacking librtmp1:i386 (2.4+20151223.gitfa8646d-1ubuntu0.1) over (2.4+20151223.gitfa8646d-1build1) ...
==> default: Preparing to unpack .../openssl_1.0.2g-1ubuntu4.8_i386.deb ...
==> default: Unpacking openssl (1.0.2g-1ubuntu4.8) over (1.0.2g-1ubuntu4.6) ...
==> default: Preparing to unpack .../python3-problem-report_2.20.1-0ubuntu2.6_all.deb ...
==> default: Unpacking python3-problem-report (2.20.1-0ubuntu2.6) over (2.20.1-0ubuntu2.5) ...
==> default: Preparing to unpack .../python3-apport_2.20.1-0ubuntu2.6_all.deb ...
==> default: Unpacking python3-apport (2.20.1-0ubuntu2.6) over (2.20.1-0ubuntu2.5) ...
==> default: Preparing to unpack .../apport_2.20.1-0ubuntu2.6_all.deb ...
==> default: Unpacking apport (2.20.1-0ubuntu2.6) over (2.20.1-0ubuntu2.5) ...
==> default: Preparing to unpack .../git-man_1%3a2.7.4-0ubuntu1.1_all.deb ...
==> default: Unpacking git-man (1:2.7.4-0ubuntu1.1) over (1:2.7.4-0ubuntu1) ...
==> default: Preparing to unpack .../git_1%3a2.7.4-0ubuntu1.1_i386.deb ...
==> default: Unpacking git (1:2.7.4-0ubuntu1.1) over (1:2.7.4-0ubuntu1) ...
==> default: Preparing to unpack .../libnl-genl-3-200_3.2.27-1ubuntu0.16.04.1_i386.deb ...
==> default: Unpacking libnl-genl-3-200:i386 (3.2.27-1ubuntu0.16.04.1) over (3.2.27-1) ...
==> default: Preparing to unpack .../libnl-3-200_3.2.27-1ubuntu0.16.04.1_i386.deb ...
==> default: Unpacking libnl-3-200:i386 (3.2.27-1ubuntu0.16.04.1) over (3.2.27-1) ...
==> default: Preparing to unpack .../linux-firmware_1.157.11_all.deb ...
==> default: Unpacking linux-firmware (1.157.11) over (1.157.8) ...
==> default: Preparing to unpack .../linux-libc-dev_4.4.0-79.100_i386.deb ...
==> default: Unpacking linux-libc-dev:i386 (4.4.0-79.100) over (4.4.0-75.96) ...
==> default: Preparing to unpack .../lxcfs_2.0.7-0ubuntu1~16.04.1_i386.deb ...
==> default: Unpacking lxcfs (2.0.7-0ubuntu1~16.04.1) over (2.0.6-0ubuntu1~16.04.1) ...
==> default: Preparing to unpack .../software-properties-common_0.96.20.7_all.deb ...
==> default: Unpacking software-properties-common (0.96.20.7) over (0.96.20.5) ...
==> default: Preparing to unpack .../python3-software-properties_0.96.20.7_all.deb ...
==> default: Unpacking python3-software-properties (0.96.20.7) over (0.96.20.5) ...
==> default: Preparing to unpack .../sosreport_3.4-1~ubuntu16.04.1_i386.deb ...
==> default: Unpacking sosreport (3.4-1~ubuntu16.04.1) over (3.2+git276-g7da50d6-3ubuntu1) ...
==> default: Preparing to unpack .../uidmap_1%3a4.2-3.1ubuntu5.3_i386.deb ...
==> default: Unpacking uidmap (1:4.2-3.1ubuntu5.3) over (1:4.2-3.1ubuntu5) ...
==> default: Preparing to unpack .../unattended-upgrades_0.90ubuntu0.6_all.deb ...
==> default: Unpacking unattended-upgrades (0.90ubuntu0.6) over (0.90ubuntu0.3) ...
==> default: Preparing to unpack .../cloud-initramfs-copymods_0.27ubuntu1.4_all.deb ...
==> default: Unpacking cloud-initramfs-copymods (0.27ubuntu1.4) over (0.27ubuntu1.3) ...
==> default: Preparing to unpack .../cloud-initramfs-dyn-netconf_0.27ubuntu1.4_all.deb ...
==> default: Unpacking cloud-initramfs-dyn-netconf (0.27ubuntu1.4) over (0.27ubuntu1.3) ...
==> default: Preparing to unpack .../grub-legacy-ec2_0.7.9-113-g513e99e0-0ubuntu1~16.04.1_all.deb ...
==> default: Leaving 'diversion of /usr/sbin/grub-set-default to /usr/sbin/grub-set-default.real by grub-legacy-ec2'
==> default: Unpacking grub-legacy-ec2 (0.7.9-113-g513e99e0-0ubuntu1~16.04.1) over (0.7.9-90-g61eb03fe-0ubuntu1~16.04.1) ...
==> default: Preparing to unpack .../overlayroot_0.27ubuntu1.4_all.deb ...
==> default: Package configuration┌──────────────────────────┤ Configuring grub-pc ├──────────────────────────┐│││ The grub-pc package is being upgraded. This menu allows you to select││ which devices you'd like grub-install to be automatically run for, if││ any.││││ Running grub-install automatically is recommended in most situations, to ││ prevent the installed GRUB core image from getting out of sync with GRUB ││ modules or grub.cfg.││││ If you're unsure which drive is designated as boot drive by your BIOS, ││ it is often a good idea to install GRUB to all of them.││││ Note: it is possible to install GRUB to partition boot records as well, ││ and some appropriate partitions are offered here. However, this forces ││ GRUB to use the blocklist mechanism, which makes it less reliable, and ││ therefore is not recommended.││││<Ok>│││└───────────────────────────────────────────────────────────────────────────┘
==> default: addgroup: 
==> default: The groupinput' already exists as a system group. Exiting.
==> default: update-initramfs: deferring update (trigger activated)
^[[C^[[A^[[D Setting up libfreetype6:i386 (2.6.1-0.1ubuntu2.3) ...
==> default: Setting up grub-common (2.02~beta2-36ubuntu3.11) ...
==> default: update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
==> default: Setting up grub2-common (2.02~beta2-36ubuntu3.11) ...
==> default: Setting up grub-pc-bin (2.02~beta2-36ubuntu3.11) ...
==> default: Setting up grub-pc (2.02~beta2-36ubuntu3.11) ...
==> default:

**Comment by SteveWooding** [comment]
This is the same issue as this one, in the other Vagrant repository: https://github.com/udacity/fullstack-nanodegree-vm/issues/69

Hopefully @karlud will commit the same fix to this repository soon.

**Comment by em-torres** [comment]
@cocacolabe @SteveWooding I've opened a [Pull Request](https://github.com/udacity/OAuth2.0/pull/9) to fix this issue.

**Comment by SteveWooding** [comment]
I've submitted my own, more tightly focused pull request, which might have a better chance of getting accepted. I have emailed FSND support about this issue as well, but yet to receive a response. Hopefully it will be dealt with soon.
